const OPTIMIZE_PROJECT_REQUEST = 'OPTIMIZE_PROJECT_REQUEST';
const OPTIMIZE_PROJECT_SUCCESS = 'OPTIMIZE_PROJECT_SUCCESS';
const OPTIMIZE_PROJECT_FAILURE = 'OPTIMIZE_PROJECT_FAILURE';

const OPTIMIZATION_BY_PROJECT_ID_REQUEST = 'OPTIMIZATION_BY_PROJECT_ID_REQUEST';
const OPTIMIZATION_BY_PROJECT_ID_SUCCESS = 'OPTIMIZATION_BY_PROJECT_ID_SUCCESS';
const OPTIMIZATION_BY_PROJECT_ID_FAILURE = 'OPTIMIZATION_BY_PROJECT_ID_FAILURE';

export {
    OPTIMIZE_PROJECT_REQUEST, OPTIMIZE_PROJECT_SUCCESS, OPTIMIZE_PROJECT_FAILURE,
    OPTIMIZATION_BY_PROJECT_ID_REQUEST, OPTIMIZATION_BY_PROJECT_ID_SUCCESS, OPTIMIZATION_BY_PROJECT_ID_FAILURE
}