const FETCH_PROJECT_BY_ID_REQUEST = 'FETCH_PROJECT_BY_ID_REQUEST';
const FETCH_PROJECT_BY_ID_SUCCESS = 'FETCH_PROJECT_BY_ID_SUCCESS';
const FETCH_PROJECT_BY_ID_FAILURE = 'FETCH_PROJECT_BY_ID_FAILURE';

const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST';
const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
const UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE';

export {
    FETCH_PROJECT_BY_ID_REQUEST, FETCH_PROJECT_BY_ID_SUCCESS, FETCH_PROJECT_BY_ID_FAILURE,
    UPDATE_PROJECT_REQUEST, UPDATE_PROJECT_SUCCESS, UPDATE_PROJECT_FAILURE
}