const REMOVE_TASK_REQUEST = 'REMOVE_TASK_REQUEST';
const REMOVE_TASK_FAILURE = 'REMOVE_TASK_FAILURE';
const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS';

export {
    REMOVE_TASK_REQUEST, REMOVE_TASK_FAILURE, REMOVE_TASK_SUCCESS
}