const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
const FETCH_TASKS_FAILURE = 'FETCH_USERS_FAILURE';

const SUBMIT_TASK_REQUEST = 'SUBMIT_TASK_REQUEST';
const SUBMIT_TASK_FAILURE = 'SUBMIT_TASK_FAILURE';
const SUBMIT_TASK_SUCCESS = 'SUBMIT_TASK_SUCCESS';

export {
    FETCH_TASKS_REQUEST, FETCH_TASKS_SUCCESS, FETCH_TASKS_FAILURE,
    SUBMIT_TASK_REQUEST, SUBMIT_TASK_FAILURE, SUBMIT_TASK_SUCCESS
}