const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
const FETCH_PROJECT_FAILURE = 'FETCH_PROJECT_FAILURE';

const SUBMIT_PROJECT_REQUEST = 'SUBMIT_PROJECT_REQUEST';
const SUBMIT_PROJECT_FAILURE = 'SUBMIT_PROJECT_FAILURE';
const SUBMIT_PROJECT_SUCCESS = 'SUBMIT_PROJECT_SUCCESS';

export {
    FETCH_PROJECTS_REQUEST, FETCH_PROJECT_SUCCESS, FETCH_PROJECT_FAILURE,
    SUBMIT_PROJECT_REQUEST, SUBMIT_PROJECT_FAILURE, SUBMIT_PROJECT_SUCCESS
}