const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
const FETCH_PROJECT_FAILURE = 'FETCH_PROJECT_FAILURE';

export {
    FETCH_PROJECTS_REQUEST, FETCH_PROJECT_SUCCESS, FETCH_PROJECT_FAILURE
}