const AUTHENTICATE_USER_REQUEST = 'AUTHENTICATE_USER_REQUEST';
const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE';

export {
    AUTHENTICATE_USER_REQUEST, AUTHENTICATE_USER_SUCCESS, AUTHENTICATE_USER_FAILURE
}