const FETCH_ALL_PROJECTS_REQUEST = 'FETCH_ALL_PROJECTS_REQUEST';
const FETCH_ALL_PROJECTS_SUCCESS = 'FETCH_ALL_PROJECTS_SUCCESS';
const FETCH_ALL_PROJECTS_FAILURE = 'FETCH_ALL_PROJECTS_FAILURE';

export {
    FETCH_ALL_PROJECTS_REQUEST, FETCH_ALL_PROJECTS_SUCCESS, FETCH_ALL_PROJECTS_FAILURE
}